# Generated by Django 6.0 on 2025-12-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('anon_id', models.CharField(max_length=12, unique=True)),
                ('pin_hash', models.TextField()),
                ('anon_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'diary_users',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('encrypted_title', models.BinaryField()),
                ('encrypted_content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diary.diaryuser')),
            ],
            options={
                'db_table': 'diary_entries',
            },
        ),
    ]
